### ISSUE TITLE
Email Comment: Support for free software and other comments

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#212] opened 2016-04-17 01:08 UTC
[Email Comment: Received on 4/15/2016, at 2:31PM ET]

To whom it may concern:
- I urge the federal government to recognize and include the term "free software" and the Free Software Definition, indicating that this policy is designed to protect the autonomy of government and the rights of its people.
- The proposal is to release 20% of custom code each year: I recommend releasing all code as free.
- Additionally, free documentation should be included in the policy.
- The federal government needs to address its contradictory habit of requiring or recommending the use of proprietary software, including non-free JavaScript.
- The government should not require use of GitHub in order to contribute to government projects under this initiative -- our code repository criteria explain important concerns in this area.

Regards,
Victor Escobar

**Comment by danbernier** [comment] 2016-04-17 12:52
_Comment moved to #207._

**Comment by danbernier** [comment] 2016-04-17 12:55
Also, this issue should be marked as a duplicate of #207. I'll move my previous comment to that issue.

**Closed as completed** 2016-04-19 04:03 UTC
